desc member;
ALTER TABLE MEMBER
ADD(
    MEM_ROLE VARCHAR2(20 CHAR)
);
UPDATE MEMBER
SET
MEM_ROLE='ROLE_ADMIN'
WHERE MEM_ID = 'c001';
commit;
SELECT MEM_ID, MEM_ROLE
FROM MEMBER;

desc prod;
desc member;
ALTER TABLE MEMBER
ADD(MEM_IMG BLOB);

DESC MEMBER;
select mem_pass
from member;

ALTER TABLE MEMBER
MODIFY MEM_PASS VARCHAR2(150);

UPDATE MEMBER
SET MEM_PASS = 'SknbGf+Gu+UwwxddYCnEA/VQEEQFwQfzyqJon3AzmlXS6txg7Wd6I5SkAsZqtIsRNAQ81NH2+l9XITTvSi3k/A==';
COMMIT;

SELECT MEM_PASS
FROM MEMBER;
