desc board;
SELECT EMPNO, LEVEL, LPAD(' ', 2*level-1) || ENAME, MGR, SAL
FROM EMP
START WITH MGR IS NULL
CONNECT BY PRIOR EMPNO = MGR
ORDER SIBLINGS BY SAL ASC;

SELECT
    BO_SORT, BO_TYPE, BO_NO
    , LEVEL
    , LPAD('re:', 6*(level-1), '*nbsp;')|| DECODE(BO_SEC, 'Y', '비밀글임', BO_TITLE) BO_TITLE
    , BO_WRITER
    , BO_HIT, BO_REC
    , TO_CHAR(BO_DATE, 'YYYY-MM-DD HH:MI') BO_DATE
    , BO_SEC
FROM BOARDVIEW
WHERE BO_TYPE = 'BOARD'
START WITH BO_PARENT IS NULL
CONNECT BY PRIOR BO_NO = BO_PARENT

ORDER SIBLINGS BY BO_SORT ASC, BO_NO DESC; 

DELETE FROM ATTATCH
WHERE BO_NO =1867; 
SELECT * FROM BOARD
WHERE BO_NO = 1867;
UPDATE BOARD
    SET
        BO_TITLE 	= "파일 없는 글"
        ,BO_WRITER 	= "글쓴이"
        ,BO_CONTENT 	= "할로"
        ,BO_SEC 		= 'N'
    WHERE BO_NO = 1867;