UPDATE BOARD
SET
BO_TITLE = 'TEST'
WHERE BO_NO = 1871;
ROLLBACK;

DELETE 
FROM BOARD
WHERE BO_NO=1871
    AND BO_PASS='123';

ALTER TABLE BOARD
ADD BO_ISDELETE CHAR(1 BYTE) DEFAULT 'N';


SELECT BO_NO, BO_PARENT
FROM BOARDVIEW
START WITH BO_PARENT =1871
CONNECT BY PRIOR BO_NO = BO_PARENT
ORDER SIBLINGS BY BO_SORT ASC, BO_NO DESC;

-- 스칼라쿼리
SELECT EMPNO, ENAME, MGR, (
    SELECT COUNT(*)
    FROM EMP B
    WHERE B.MGR = A.EMPNO
) CNT
FROM EMP A;

MERGE INTO EMP C
USING (
    SELECT EMPNO, (
        SELECT COUNT(*)
        FROM EMP B
        WHERE B.MGR = A.EMPNO
    ) CNT
    FROM EMP A
) D
ON (C.EMPNO='7369' AND C.EMPNO = D.EMPNO)
WHEN MATCHED THEN
UPDATE SET ENAME = '수정'
DELETE WHERE D.CNT = 0;
ROLLBACK;

-- 실제 적용시켜보기 CNT=0이면 삭제 >0 이면 상태 변경
SELECT BO_NO, (
    SELECT COUNT(*) -1
    FROM BOARD B
    START WITH BO_NO = A.BO_NO
    CONNECT BY PRIOR BO_NO = BO_PARENT
) CNT
FROM BOARD A
ORDER BY BO_NO DESC
;

MERGE INTO BOARD C
USING (
    SELECT BO_NO, (
        SELECT COUNT(*) -1
        FROM BOARD B
        START WITH BO_NO = A.BO_NO
        CONNECT BY PRIOR BO_NO = BO_PARENT
    ) CNT
    FROM BOARD A
) D
ON (C.BO_NO = 1863 AND C.BO_NO = D.BO_NO)
WHEN MATCHED THEN
    UPDATE SET
    BO_TITLE = '삭제된 글의 제목'
    , BO_CONTENT = '삭제된 글의 내용'
    DELETE WHERE D.CNT = 0;

SELECT BO_TITLE
FROM BOARD
WHERE BO_NO = 1863;
ROLLBACK;

ALTER TABLE BOARD 
MODIFY(BO_ISDELETE CHAR(1) DEFAULT 'N');
ALTER TABLE BOARD RENAME COLUMN BO_ISDELETE TO BO_DELETE;


rollback;

