CREATE TABLE NOTICE(
BO_NO	NUMBER(6),
BO_TITLE	VARCHAR2(100 CHAR) NOT NULL,
BO_CONTENT	CLOB ,
BO_DATE	DATE DEFAULT SYSDATE,
BO_HIT	NUMBER(4) DEFAULT 0,
BO_REC	NUMBER(4) DEFAULT 0,
CONSTRAINT PK_NOTICE PRIMARY KEY(BO_NO)
);

CREATE TABLE BOARD(
BO_NO	NUMBER(6),
BO_TITLE	VARCHAR2(100 CHAR) NOT NULL,
BO_WRITER	VARCHAR2(20 CHAR) NOT NULL,
BO_PASS	VARCHAR2(200 CHAR) NOT NULL,
BO_CONTENT	CLOB,
BO_DATE	DATE DEFAULT SYSDATE,
BO_HIT	NUMBER(4) DEFAULT 0,
BO_REC	NUMBER(4) DEFAULT 0,
BO_REP	NUMBER(4) DEFAULT 0,
BO_SEC	CHAR(1) DEFAULT 'N', --'Y'/'N' 
BO_PARENT NUMBER(6) ,
CONSTRAINT PK_BOARD PRIMARY KEY(BO_NO),
CONSTRAINT FK_BOARD_BOARD FOREIGN KEY(BO_PARENT)
    REFERENCES BOARD(BO_NO)
);

CREATE TABLE ATTATCH(
BO_NO NUMBER(6) ,
ATT_NO NUMBER(4) , 
ATT_FILENAME VARCHAR2(150 CHAR) NOT NULL,
ATT_SAVENAME VARCHAR2(150 CHAR) NOT NULL,
ATT_SIZE NUMBER(10) NOT NULL,
ATT_CONTENTTYPE VARCHAR2(100 CHAR), 
ATT_DOWNCOUNT NUMBER(4) DEFAULT 0,
CONSTRAINT PK_ATTATCH PRIMARY KEY(ATT_NO),
CONSTRAINT FK_BOARD_ATTATCH FOREIGN KEY(BO_NO)
    REFERENCES BOARD(BO_NO)
);

CREATE TABLE REPLY2
(
BO_NO NUMBER(6) ,
REP_NO NUMBER(6) ,
REP_WRITER VARCHAR2(20 CHAR) NOT NULL,
REP_PASS VARCHAR2(200 CHAR) NOT NULL,
REP_CONTENT VARCHAR2(400 CHAR) ,
REP_DATE DATE DEFAULT SYSDATE,
CONSTRAINT PK_REPLY2 PRIMARY KEY(REP_NO),
CONSTRAINT FK_BOARD_REPLY2 FOREIGN KEY(BO_NO)
    REFERENCES BOARD(BO_NO)
);

