
SELECT A.*, ROWNUM RNUM
FROM (
    SELECT
        ROWNUM RNUM, PROD_ID, PROD_NAME, PROD_LGU
        , PROD_BUYER, PROD_COST, PROD_PRICE
        , PROD_SALE, PROD_OUTLINE, PROD_DETAIL
        , PROD_IMG, PROD_TOTALSTOCK, PROD_INSDATE
        , PROD_PROPERSTOCK, PROD_SIZE, PROD_COLOR
        , PROD_DELIVERY, PROD_UNIT, PROD_QTYIN
        , PROD_QTYSALE, PROD_MILEAGE
        , LPROD_NM
        , BUYER_ID, BUYER_NAME, BUYER_ADD1
        , BUYER_COMTEL, BUYER_CHARGER
    FROM PROD INNER JOIN LPROD ON (PROD_LGU = LPROD_GU)
              INNER JOIN BUYER ON (PROD_BUYER = BUYER_ID)
    ) A
WHERE RNUM >= 10 AND RNUM <= 20;

SELECT B.*
FROM(
    SELECT A.*, ROWNUM RUM
    FROM
        (
            SELECT MEM_ID, MEM_NAME, MEM_ADD1
            FROM MEMBER
            WHERE INSTR(MEM_ADD1, '´ëÀü') > 0
            ORDER BY ROWID DESC
        ) A
) B;



