-- a001 사용자의 기본 정보와
--그동안 구매한 상품 목록을 함께 조회
--상품 : 코드, 명, 구매가, 판매가, 마일리지
SELECT * FROM MEMBER;
SELECT * FROM CART WHERE CART_MEMBER='a001';
SELECT 
    PROD_ID, 
    PROD_NAME,
    PROD_COST,
    PROD_PRICE,
    PROD_MILEAGE
FROM PROD A LEFT OUTER JOIN CART B 
    ON A.PROD_ID = B.CART_PROD
    AND B.CART_MEMBER='a001';

SELECT MEM_ID
    FROM MEMBER A RIGHT OUTER JOIN CART B
        ON A.MEM_ID = B.CART_MEMBER
        WHERE MEM_ID='a001';

SELECT MEMBER.*, PROD_ID, PROD_NAME, PROD_COST, PROD_PRICE, PROD_MILEAGE
FROM MEMBER LEFT OUTER JOIN CART 
        ON (MEM_ID = CART_MEMBER)
    LEFT OUTER JOIN PROD ON (CART_PROD = PROD_ID)
WHERE MEM_ID='a 001';

SELECT 'private '||
    DECODE(DATA_TYPE, 'NUMBER', 'Integer ', 'String ')||
    LOWER(COLUMN_NAME)||';'
FROM cols
WHERE table_name = 'PROD';

SELECT DISTINCT MEMBER.*, PROD_ID, PROD_NAME, PROD_COST, 
PROD_PRICE, PROD_MILEAGE, LPROD_NM,
BUYER_NAME
FROM MEMBER LEFT OUTER JOIN CART 
        ON (MEM_ID = CART_MEMBER)
    LEFT OUTER JOIN PROD ON (CART_PROD = PROD_ID)
    LEFT OUTER JOIN LPROD ON (PROD_LGU = LPROD_GU)
    LEFT OUTER JOIN BUYER ON (PROD_BUYER = BUYER_ID)
WHERE MEM_ID='a001';

--한명의 정보 조회시,
--구매목록 조회(중복제거)
--상품정보 조회 시 분류명, 거래처명 조회
WITH CARTPROD AS(
    SELECT DISTINCT CART_MEMBER, CART_PROD FROM CART
), PRODALL AS(
    SELECT PROD.*, LPROD_NM
        , BUYER.*
    FROM PROD INNER JOIN LPROD ON(PROD_LGU=LPROD_GU)
            INNER JOIN BUYER ON(PROD_BUYER = BUYER_ID)
)

SELECT MEMBER.* 
    ,PRODALL.*
FROM MEMBER LEFT OUTER JOIN CARTPROD ON (MEM_ID = CART_MEMBER)
    LEFT OUTER JOIN PRODALL ON (CART_PROD = PROD_ID)
WHERE MEM_ID = 'a001';      

SELECT DISTINCT MEMBER.*, PROD_ID, PROD_NAME, PROD_COST, 
PROD_PRICE, PROD_MILEAGE, LPROD_NM,
BUYER_NAME
FROM MEMBER LEFT OUTER JOIN CART 
        ON (MEM_ID = CART_MEMBER)
    LEFT OUTER JOIN PROD ON (CART_PROD = PROD_ID)
    LEFT OUTER JOIN LPROD ON (PROD_LGU = LPROD_GU)
    LEFT OUTER JOIN BUYER ON (PROD_BUYER = BUYER_ID)
WHERE MEM_ID='a001';

SELECT 'private '||
    DECODE(DATA_TYPE, 'NUMBER', 'Integer ', 'String ')||
    LOWER(COLUMN_NAME)||';'
FROM cols
WHERE table_name = 'BUYER';

SELECT PROD_ID, BUYER_ID, BUYER_BANKNAME, BUYER_BANKNO, 
        BUYER_ADD1 
FROM PROD LEFT OUTER JOIN BUYER
    ON (BUYER_ID = PROD_BUYER)
WHERE PROD_ID='P101000001';

select PROD_BUYER from PROD
WHERE PROD_ID='P101000001';

SELECT '<tr><th>' || COMMENTS ||
    '</th><td><%=' ||
    LOWER(TABLE_NAME) ||
    '.get'|| SUBSTR(COLUMN_NAME, 1, 1)||
    LOWER(SUBSTR(COLUMN_NAME, 2)) ||
    '() %></td></tr>'
FROM USER_COL_COMMENTS
WHERE TABLE_NAME = 'PROD';