
SELECT A.*, ROWNUM RNUM
FROM (
    SELECT
        ROWNUM RNUM, PROD_ID, PROD_NAME, PROD_LGU
        , PROD_BUYER, PROD_COST, PROD_PRICE
        , PROD_SALE, PROD_OUTLINE, PROD_DETAIL
        , PROD_IMG, PROD_TOTALSTOCK, PROD_INSDATE
        , PROD_PROPERSTOCK, PROD_SIZE, PROD_COLOR
        , PROD_DELIVERY, PROD_UNIT, PROD_QTYIN
        , PROD_QTYSALE, PROD_MILEAGE
        , LPROD_NM
        , BUYER_ID, BUYER_NAME, BUYER_ADD1
        , BUYER_COMTEL, BUYER_CHARGER
    FROM PROD INNER JOIN LPROD ON (PROD_LGU = LPROD_GU)
              INNER JOIN BUYER ON (PROD_BUYER = BUYER_ID)
    ) A
WHERE RNUM >= 10 AND RNUM <= 20;

SELECT B.*
FROM(
    SELECT A.*, ROWNUM RUM
    FROM
        (
            SELECT MEM_ID, MEM_NAME, MEM_ADD1
            FROM MEMBER
            WHERE INSTR(MEM_ADD1, '대전') > 0
            ORDER BY ROWID DESC
        ) A
) B;
SELECT LPROD_GU, LPROD_NM
    FROM LPROD;

SELECT PROD_LGU, PROD_ID
FROM PROD;

-- P101의 신규상품, 코드값
--SELECT PROD_LGU || LPAD(TO_NUMBER(SUBSTR(MAX(PROD_ID),LENGTH(PROD_LGU)+1))+1, 6, '0')
--FROM PROD 
--WHERE PROD_LGU = 'P109'
--GROUP BY PROD_LGU;
SELECT 'P109' || LPAD(TO_NUMBER(SUBSTR(NVL(MAX(PROD_ID), LPAD('0', 10, '0')), LENGTH('P109')+1))+1, 6, '0')
FROM PROD 
WHERE PROD_LGU = 'P109';

select *
from prod;
select *
from buyer;

INSERT INTO PROD (PROD_ID, PROD_NAME, PROD_LGU, 
            PROD_BUYER, PROD_COST, PROD_PRICE,
            PROD_SALE, PROD_OUTLINE, PROD_IMG, 
            PROD_TOTALSTOCK, prod_properstock) 
VALUES((SELECT 'P101' || LPAD(TO_NUMBER(SUBSTR(NVL(MAX(PROD_ID), LPAD('0', 10, '0')), LENGTH('P109')+1))+1, 6, '0')
FROM PROD 
WHERE PROD_LGU = 'P101'), 'A', 'P101', 'P10101', '1', '1', '1', '1', '1', '1', '1');

commit;

SELECT 'P101' || 
    LPAD(TO_NUMBER(SUBSTR(NVL(MAX(PROD_ID), LPAD('0', 10, '0')), 
    LENGTH('P101')+1))+1, 6, '0')
FROM PROD 
WHERE PROD_LGU = 'P101';