-- 1. 남여 성별 인원수 조회
WITH MAN AS(
    SELECT COUNT(*) MAN
    FROM MEMBER
    WHERE SUBSTR(MEM_REGNO2,1,1) = '1' OR
    SUBSTR(MEM_REGNO2,1,1) = '3'
),
WOMAN AS(
    SELECT COUNT(*) WOMAN
    FROM MEMBER
    WHERE SUBSTR(MEM_REGNO2,1,1) = '2' OR
       SUBSTR(MEM_REGNO2,1,1) = '4'
)
SELECT * FROM MAN,WOMAN;
